---
name: Linter
description: Lint java code

inputs: { }

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build kotlin app
      uses: ./.github/actions/setup-kotlin

    - name: Run linter
      run: ./gradlew ktlintCheck
      shell: bash
